docs: Add Storybook documentation for Heading, Paragraph and Box
cultureamp/kaizen-design-system pull request #1150
Opened 2021-03-01 07:24 UTC by sebpearce

# Motivation and Context

Heading, Paragraph and Box are not represented on the Kaizen Site documentation, so sometimes it's difficult for engineers to figure out what they're for and how to use them.

# Checklist

- [ ] If this contains visual changes, has it been reviewed by a designer?
- [ ] If this introduces either a new component or a breaking change to an existing component, has it been reviewed by an advocate? (Ask in #prod_design_systems)
- [ ] I have considered likely risks of these changes and got someone else to QA as appropriate
- [ ] I have or will communicate these changes to the front end practice

2021-05-24 05:53 UTC, ActuallyACat requested changes

2021-05-24 05:53 UTC, ActuallyACat commented on packages/component-library/stories/Box.stories.tsx
>  export default {
Something to consider to move all the docs to the "docs" tab: https://storybook.js.org/docs/react/writing-docs/docs-page#remixing-docspage-using-doc-blocks

If these are left in the stories themselves we would start running visual regressions on them 

```
export default {
  title: 'Box (React)',
  component: Box,
  parameters: {
    docs: {
      page: () => (
        <>
          <Title />
          <Subtitle />
          <Description />
          <Primary />
          <Documentation /> // add this
          <ArgsTable story={PRIMARY_STORY} />
          <Stories />
        </>
      ),
    },
  },
};
```

2021-09-20 06:39 UTC, lloydstubber commented
Updated the PR @ActuallyACat and now these are in the docs section instead of canvas

<img width="1343" alt="Screen Shot 2021-09-20 at 4 34 57 pm" src="https://user-images.githubusercontent.com/18339250/133964377-36479bb9-c8e6-4dc2-ab8c-22a9398c8a79.png">
<img width="1333" alt="Screen Shot 2021-09-20 at 4 34 49 pm" src="https://user-images.githubusercontent.com/18339250/133964382-ce9e8608-c905-4f97-b8a0-67b325889c25.png">

2021-11-02 00:40 UTC, ActuallyACat approved these changes

2021-11-02 01:50 UTC, merged