feat: Added optional isAnimated prop to illustrations that support an…
cultureamp/kaizen-design-system pull request #1650
Opened 2021-05-26 11:41 UTC by ActuallyACat

…imations

// @TODO
* accessibility (maybe using figure since I can't add metadata to the Lottie animation?)
* fallback to static image
* error handling when asset loading fails
*  allow delay on animation
* Rename mood-roadblock.lottie to mood-cautionary.lotte in kds-assets

# Objective

# Motivation and Context

# Screenshots (if appropriate)

# Checklist

- [ ] If this contains visual changes, has it been reviewed by a designer?
- [ ] If this introduces either a new component or a breaking change to an existing component, has it been reviewed by an advocate? (Ask in #prod_design_systems)
- [ ] I have considered likely risks of these changes and got someone else to QA as appropriate
- [ ] I have or will communicate these changes to the front end practice

# Additional Considerations
- Does there need to be right-to-left (RTL) options for localization and internationalization?
- Has the test suite been updated?
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participants)?
- Have you updated any relevant documentation or left useful comments in the code?
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Accessibility)?
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in the pipeline?
- Have Storybook stories been updated?

**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask in #prod_design_systems to have a design system advocate review the PR to catch any issues.

2021-06-07 04:04 UTC, dougmacknz requested changes
Awesome to see these animated! I found a few things that should probably be addressed, otherwise it's looking good to me.

2021-06-07 04:04 UTC, dougmacknz commented on draft-packages/illustration/KaizenDraft/Illustration/AnimatedBase.tsx
> +  isAnimated?: boolean
Do you actually need `isAnimated` here?

2021-06-08 00:34 UTC, ActuallyACat commented on draft-packages/illustration/KaizenDraft/Illustration/AnimatedBase.tsx
> +        <circle fill="#f9f9f9" cx="48" cy="48" r="48" />
Thoughts on what to include in the loading title? I'm going to hazard a guess in _most_ scenarios the illustration is purely decorative and we won't want to add annotations to them/leave an empty alt on them. 

I can see maybe two options and I'm undecided on the best approach: 
1. Pass-through `alt` to failed/success/loading state elements. So if our users supplied `alt="Successfully submitted survey"` each of those element states would display "Successfully submitted survey". Similarly for empty alts. I'm unsure if a screen reader would re-announce those states.
2. Wrap the whole thing in a `figure` and have one `figcaption` for this component, and completely ignore the individual img/svg within this component (maybe add `aria-hidden="true"` to the loading element and inline svg)

2021-06-08 02:08 UTC, dougmacknz commented on draft-packages/illustration/KaizenDraft/Illustration/AnimatedBase.tsx
> +        <circle fill="#f9f9f9" cx="48" cy="48" r="48" />
Yeah I like option 2 as well 👍

2021-06-09 00:39 UTC, ActuallyACat commented on draft-packages/illustration/KaizenDraft/Illustration/Spot.tsx
> +  if (isAnimated) {
I've added a warning for those cases, and fallback to a static asset.

2021-06-09 02:10 UTC, dougmacknz submitted a review, later dismissed
awesome awesome awesome

2021-06-09 04:59 UTC, makenosound commented
We don’t necessarily need to tackle it straight away, but I wonder if we should have `prefers-reduced-motion` fallbacks for these: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

2021-06-09 05:01 UTC, ActuallyACat commented
> We don’t necessarily need to tackle it straight away, but I wonder if we should have prefers-reduced-motion fallbacks for these: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

Ah! Yes I completely overlooked this - I'll add those now and fallback to static images. Seems straightforward enough to squeeze in now.

2021-06-09 05:07 UTC, dougmacknz commented
>We don’t necessarily need to tackle it straight away, but I wonder if we should have prefers-reduced-motion fallbacks for these

I considered this but came to a conclusion that these were _probably_ low movement enough, though if it were looping it would probably cross that threshold. If we leave them in I could check with Intopia if we want.

2021-06-09 05:12 UTC, ActuallyACat commented
> I considered this but came to a conclusion that these were probably low movement enough, though if it were looping it would probably cross that threshold. If we want, we could leave them in and I can check with Intopia.

I'll hold off for now in that case. I'm curious to hear what their thoughts on the movement threshold would be. Scene illustrations would definitely pass that threshold.

2021-06-09 06:13 UTC, dlimiter approved these changes

2021-06-09 06:33 UTC, merged