Add Pagination component
cultureamp/kaizen-design-system pull request #1733
Opened 2021-06-29 07:05 UTC by JakePitman

- Copies the Pagination component from Perf, and changes it to accept an onPageChange callback. This allows us to pass in the behaviour from outside the component (we will use this to update the current page in the parent state, and re-render the appropriate page)
- Adds a default Pagination story

2021-06-30 00:57 UTC, jakubriedl commented
Is it expected to look like this after click?
<img width="455" alt="Snímek obrazovky 2021-06-30 v 10 56 24 dop" src="https://user-images.githubusercontent.com/2728690/123885989-db707e00-d991-11eb-8fb3-14afd26cd8bd.png">

2021-07-02 00:03 UTC, sampnorris requested changes
@JakePitman - Let's pair on that bug we found where truncation was happening for when there were 3 pages.

2021-07-02 00:03 UTC, sampnorris commented on draft-packages/pagination/docs/pagination.stories.tsx
> +        // scroll to top of page
Remove these comments, not needed.

2021-07-02 00:03 UTC, sampnorris commented on draft-packages/pagination/docs/pagination.stories.tsx
> +      pageCount={50}
Let's add a storybook control for this :)

2021-07-02 02:23 UTC, dougmacknz commented
@JakePitman @sampnorris @jakubriedl @allybeaton 

Disclaimer: I haven't reviewed this PR at all yet, only seen this part:

> This PR is only for getting the existing Pagination component into Kaizen. Behavioural or code-health improvements are out of scope

I'm going to be a bit of a party pooper here because we need to crack down on the tech debt we add to Kaizen. New component contributions to Kaizen are not something that should be done lightly. When taking on a new component contribution we need to focus on getting everything as "correct" as possible right out of the gate, having reviewed many different use cases around the platform, the documentation, designer input, etc. We absolutely want to avoid copy + pastes of a single implementation from a consuming repo, it ultimately creates a large mess for us down the line.

It might be the case that that comment is out of date because I see quite a few commits coming through here, let me know if that is the case. However, if you don't have capacity to create this component in a way that would be considered future-proofed for many different use cases, please just create this in your repo and we can come back to this at a time where we can invest in those things.

2021-07-02 02:36 UTC, sampnorris commented
@dougmacknz I completely understand the need,

We planned to move this component here then implement it in 2 places: 

1- We will replace the existing implementation where this was copied from
2- We will be using this in unified home

This _has_ been tweaked to consider multiple use cases, this should be usable anywhere - and this already is up to design standards, and seems to be pretty robust code.

Happy to pull this up to kaizen standards before merge, what are the requirements here for documentation, and accessibility, would you mind reviewing the current state and adding your input as to what we need to do to get this to standard?

2021-07-02 02:37 UTC, sebpearce commented
Just wanted to mention that there was a failure of communication here on our part ("our" meaning Kaizen advocates excluding @JakePitman).

For context, basically there was a group decision made a while back that new components should be built in consuming repos and polished until they meet certain standards required for Kaizen components around reusability, accessibility, etc. But we haven't done a good job of communicating that. I'm now thinking about how that info could be made obvious (including to us, since we forgot to mention it!).

2021-07-02 02:56 UTC, sebpearce commented
> Happy to pull this up to kaizen standards before merge, what are the requirements here for documentation, and accessibility, would you mind reviewing the current state and adding your input as to what we need to do to get this to standard?

@sampnorris The reason for the change in the way we do it (build it in consumer first) is that we don't actually know what a "ready for Kaizen" standard looks like until the thing has been used in prod for a while. The approach is basically "let's assume changes will need to be made, and make that easier on ourselves when it does happen".

2021-07-07 04:30 UTC, dmisdm commented on draft-packages/pagination/KaizenDraft/PageIndicator.tsx
> +    aria-label={`${ariaLabelPage} ${page}`}
I don't know how important this is, but `ariaLabelPage` is optional, and used here as if it isn't. It's possible that this template literal might spit out `undefined 1`, `null 2` etc.
```suggestion
    aria-label={`${ariaLabelPage || "Page"} ${page}`}
```

2021-07-07 05:16 UTC, dmisdm commented on draft-packages/pagination/package.json
> +    "@kaizen/design-tokens": "^2.5.0",
I think the current version of design-tokens is 2.9.3. If theres no reason not to bump this, i think we should.
```suggestion
    "@kaizen/design-tokens": "^2.9.3",
```

2021-07-07 05:17 UTC, dmisdm commented on draft-packages/pagination/package.json
> +    "@kaizen/design-tokens": "^2.5.0",
I realised this was a peer sorry so probably doesn't matter!

2021-07-07 05:27 UTC, dmisdm commented on draft-packages/pagination/KaizenDraft/Pagination.tsx
> +        aria-disabled={previousPageDisabled}
I'm pretty sure `disabled` should be used in favor of `aria-disabled` as `<button>` natively supports the former.
Disagree with me though, i'm not 100% sure.

2021-07-07 05:32 UTC, dmisdm requested changes
Left some comments but this is some awesome stuff 🤓😃

2021-07-07 05:37 UTC, dmisdm commented on draft-packages/pagination/KaizenDraft/styles.scss
> +  border: $kz-var-border-focus-ring-border-width solid $kz-var-color-cluny-200;
Your decision to make, but `$kz-var-border-focus-ring-border-style` can be used in place of `solid` (but maybe you want `solid` to be declared explicitly).
https://cultureamp.design/storybook/?path=/story/design-tokens-api--page

2021-07-08 08:27 UTC, dougmacknz reviewed
Here's my thoughts so far. I haven't really reviewed the CSS because I would love to see us reuse the `IconButton` instead (more information in one of the review comments).

Let's have a chat about all this when you're free and we can talk about our options if you don't have capacity to take on addressing all of these.

2021-07-08 08:27 UTC, dougmacknz commented on draft-packages/pagination/KaizenDraft/Pagination.tsx
> +  ariaLabelPage?: string
Similar to Dan's comment on `PageIndicator`, these aria label props should be required I'd imagine.

2021-07-08 08:27 UTC, dougmacknz commented on draft-packages/pagination/KaizenDraft/Pagination.tsx
> +      1 + 2 * truncateSize + 2 * siblingPagesRange + 2 * boundaryPagesRange >=
Feels like all the calculations happening here belong in a separate file with tests.

2021-09-24 07:34 UTC, closed without merging