WIP: Setup basic single date picker solution and style input
cultureamp/kaizen-design-system pull request #2499
Opened 2022-01-31 23:26 UTC by lloydstubber

# Objective

# Motivation and Context

# Screenshots (if appropriate)

# Checklist

- [ ] If this contains visual changes, has it been reviewed by a designer?
- [ ] If this introduces either a new component or a breaking change to an existing component, has it been reviewed by an advocate? (Ask in #prod_design_systems)
- [ ] I have considered likely risks of these changes and got someone else to QA as appropriate
- [ ] I have or will communicate these changes to the front end practice

# Additional Considerations
- Does there need to be right-to-left (RTL) options for localization and internationalization?
- Has the test suite been updated?
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participants)?
- Have you updated any relevant documentation or left useful comments in the code?
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Accessibility)?
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in the pipeline?
- Have Storybook stories been updated?

**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask in #prod_design_systems to have a design system advocate review the PR to catch any issues.

2022-01-31 23:53 UTC, lloydstubber commented on packages/date-picker/src/DatePicker.scss
> +    &:not(.reversed) {
There is no reversed/secondary design at the minute but no doubt will be. Unsure if it's worth removing.

2022-01-31 23:59 UTC, lloydstubber commented on packages/date-picker/src/DatePicker.scss
> +      $start: 1rem + $input-icon-size,
1rem is to handle the styling for icon at the start of input which isn't relative to `ca-grid`

2022-02-01 06:00 UTC, ActuallyACat requested changes

2022-02-01 06:11 UTC, jmitsios commented
@lloydstubber

- _(See video attached)_ I'm noticing a situation where after I choose a date and I realise it wasn't the one I wanted.. I'd click back into the text field to re-trigger the calendar, but instead it just clears the focus state. Forcing another click to open it again.
- The calendar also seems to be overlapping the bottom of the focus ring too.
- I'm assuming to not make any design review comments about the calendar itself in the storybook link?
https://user-images.githubusercontent.com/95595231/151920540-075df21f-dba9-4325-b06a-33ecde218f0c.mov

2022-02-01 22:19 UTC, jmitsios approved these changes
The styling of the inputs is spot on 👍

2022-02-01 23:43 UTC, NatalieLoyzaga commented on packages/date-picker/src/DatePicker.scss
> +@import "~@kaizen/draft-button/KaizenDraft/Button/styles";
I have removed the button import as it was not being used

2022-02-06 22:28 UTC, closed without merging

2022-02-06 22:33 UTC, lloydstubber commented
Closed in favour of https://github.com/cultureamp/kaizen-design-system/pull/2511