doc: update stories to use storyWrapper
cultureamp/kaizen-design-system pull request #2575
Opened 2022-03-01 21:42 UTC by NatalieLoyzaga

# Objective

# Motivation and Context

# Screenshots (if appropriate)

# Checklist

- [ ] If this contains visual changes, has it been reviewed by a designer?
- [ ] If this introduces either a new component or a breaking change to an existing component, has it been reviewed by an advocate? (Ask in #prod_design_systems)
- [ ] I have considered likely risks of these changes and got someone else to QA as appropriate
- [ ] I have or will communicate these changes to the front end practice

# Additional Considerations
- Does there need to be right-to-left (RTL) options for localization and internationalization?
- Has the test suite been updated?
- Have you done cross-browser testing for our [supported browsers](https://academy.cultureamp.com/hc/en-us/articles/204539569-Supported-browsers-for-Participants)?
- Have you updated any relevant documentation or left useful comments in the code?
- Have you reviewed Culture Amp's Web Accessibility guide [Current Compliance, Going Forward, Statement and Answers for Customers](https://cultureamp.atlassian.net/wiki/spaces/Prod/pages/428572998/Web+Accessibility)?
- If this contains substantial visual changes, especially far reaching ones, have you unlocked the Chromatic step in the pipeline?
- Have Storybook stories been updated?

**If you're new to Kaizen, please ask #prod_design_systems to set up an onboarding session to get you up to speed.** If you have an urgent PR to merge before that happens, it is safest to ask in #prod_design_systems to have a design system advocate review the PR to catch any issues.

2022-03-03 02:38 UTC, HeartSquared requested changes
You'll want to fix your commit messages and PR title to include the subject. Makes it much easier to find :)

---

I think you might want to make sure we still have the multiline/forced multiline stories, since they actually do have visual differences. You could possibly incorporate it into your sticker sheet.

You'll also want to still leave a story for the `autoHide` prop (separately, since it shows functionality; just don't include it for Chromatic).

The `persistent` prop does not differ visually between variants, so it could just be a Row as opposed to a column.

The link is unnecessary since that is just part of `children` from what I can see.

Also, I'm pretty sure `automationId` is a testing id, so that's unnecessary to define in our stories :)

2022-03-04 03:33 UTC, NatalieLoyzaga commented
@HeartSquared I have updated the story to include multi line, autoHide separate story and removed the Persistent col.

2022-03-06 23:59 UTC, HeartSquared requested changes
Just some small changes :)

2022-03-06 23:59 UTC, HeartSquared commented on packages/notification/docs/InlineNotification.stories.tsx
> +        <StoryWrapper.RowHeader headings={["Dismissible"]} />
```suggestion
```

Since `Persistent` is now a row, this doesn't make sense to be the column heading.

2022-03-06 23:59 UTC, HeartSquared commented on packages/notification/docs/InlineNotification.stories.tsx
>    </InlineNotification>
```suggestion
  </InlineNotification>
  <p>Content below the notification</p>
```

So that it doesn't look like it goes completely blank :)

2022-03-08 23:10 UTC, HeartSquared approved these changes
LGTM :)

2022-03-09 04:06 UTC, merged