feat: add isReversed prop to FilterMultiSelect
cultureamp/kaizen-design-system pull request #3240
Opened 2023-01-27 01:39 UTC by BrendanTimmons

## Why
Need `isReversed` functionality from `Select` component to the `FilterMultiSelect` component because we're using both in a filters area on a purple background.

## What
Add the required `isReversed` functionality to `FilterMultiSelect`

### Default:
![Screen Shot 2023-01-27 at 12 38 04 pm](https://user-images.githubusercontent.com/5242169/214991599-2965bbdb-4068-4364-ad54-2ddadb4f2af0.png)

### Reversed:
![Screen Shot 2023-01-27 at 12 35 28 pm](https://user-images.githubusercontent.com/5242169/214991232-eea0cea2-14e1-4e3f-a0c7-aae47e3c93e0.png)

2023-02-12 22:53 UTC, NatalieLoyzaga requested changes
Hey @BrendanTimmons I just left a few comments :)

2023-02-12 22:53 UTC, NatalieLoyzaga commented on packages/select/src/FilterMultiSelect/components/Trigger/TriggerButtonBase/TriggerButtonBase.module.scss
> +    background-color: rgba($color-white-rgb, 0.1);
The [UI kit](https://www.figma.com/file/ZRfnoNUXbGZv4eVWLbF4Az/%EF%B8%8F%F0%9F%96%BC%EF%B8%8F-Component-Gallery?node-id=1206%3A155907&t=rVqn5LiNNw3fUPxn-0) has 0.2 opacity 

`background-color: rgba($color-white-rgb, 0.2);`

2023-02-12 22:53 UTC, NatalieLoyzaga commented on packages/select/src/FilterMultiSelect/components/Trigger/TriggerButtonBase/TriggerButtonBase.module.scss
> +  .error {
We don't require the `.error` and `.caution` styles

2023-02-12 22:53 UTC, NatalieLoyzaga commented on packages/select/src/FilterMultiSelect/components/Trigger/_variables.scss
> +$selectors--button-focus: "&:focus, &#{$story-className--button-focus}";
This is a double up of line 10

2023-02-28 00:18 UTC, closed without merging

2023-02-28 00:18 UTC, BrendanTimmons commented
Closing this as we went with a different solution and just used the filter multi select for all our selects instead of a mix of select / multiselects.